with-expecter: true
quiet: False
disable-version-string: True
mockname: "{{.InterfaceName}}"
filename: "mock_{{.MockName}}.go"
outpkg: "{{.PackageName}}//mocks"
dir: "{{.PackageName}}//mocks"

packages:
  github.com/alexSkiba15/article-golang-test/adapters:
    config:
    interfaces:
      ArticleRepository:
        config:
