version: '3.8'
services:
  postgres:
    image: postgres:16
    ports:
      - "5498:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=stocks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
