version: 3

tasks:
  generate:
    aliases:
      - generate
    desc: "Generate code"
    cmds:
      - protoc -I=src/api/app ./src/api/app/first.proto --go_out=src/api/app/gen --go_opt=paths=source_relative --go-grpc_out=src/api/app/gen --go-grpc_opt=paths=source_relative
  linter:
    aliases:
      - linter
    desc: "Lint code"
    cmds:
      - golangci-lint run
  imports:
    aliases:
      - imports
    desc: "Sort imports"
    cmds:
      - goimports -w .
  fmt:
    desc: auto-format all go files
    sources:
      - "**/*.go"
    cmds:
      - go fmt ./...
  wire:
    desc: generate wire file
    sources:
      - "**/*.go"
    cmds:
      - cd "./di" && wire
